### ISSUE TITLE
Layers tab in editor doesn't close properly on tab swap

### ISSUE THREAD

**Issue by CamerTheDragon** [jacob-grahn/platform-racing-4#10]
When selecting the layers tab in the editor and then selecting another tab, the tab row will be 1 increment too high until another tab is selected.

**Comment by jc66266** [comment]
Happens when going from Layers -> Blocks
(Layers -> Draw -> Blocks does not reproduce the issue)

**Comment by CamerTheDragon** [comment]
For me the issue still occurs with others such as Draw, as the tabs are not flush with the bottom of the screen.

**Comment by jacob-grahn** [comment]
Now there are no tabs, so this is fixed as a side effect!
