### ISSUE TITLE
Multi-hitting rotates

### ISSUE THREAD

**Issue by jc66266** [jacob-grahn/platform-racing-4#15]
Rotate block is not throttled (put into a timed null state) after being bumped, so it's possible to bump it multiple times as you rotate (causing multiple rotations).

![8hFkiBc](https://github.com/user-attachments/assets/bfb7cfb0-dea3-4ccc-a821-b51022969529)

**Comment by jacob-grahn** [comment]
Thanks, fixed with https://github.com/jacob-grahn/platform-racing-4/commit/0eb92f7e1074eaacd0b56b58b93dd40bfa43e32c
