### ISSUE TITLE
Move block bump animation desynced in position when move occurs partway through the animation

### ISSUE THREAD

**Issue by CamerTheDragon** [jacob-grahn/platform-racing-4#20]
When bumping the move block, it plays the bump animation in full in the place you hit the move block, but if the move block moves during the animation you see the tile in the new position as well, temporarily showing 2 move blocks instead of just 1.
Fix would be either to move the instantiated animation block 1 block length in the direction of the move, or to remove it and make a new one then play the animation from the point it left off using something like "anim_player.seek(time)".

**Comment by jacob-grahn** [comment]
Thanks, fixed with https://github.com/jacob-grahn/platform-racing-4/commit/5a806eb107d7e058abf526389999bdae449eef3e

(just removing the phantom bounce effect, it looks fine that way to me)
