### ISSUE TITLE
Layer depht broken

### ISSUE THREAD

**Issue by ctrlraul** [jacob-grahn/platform-racing-4#30]
After [this commit](https://github.com/ctrlraul/platform-racing-4/commit/ee445a79f2a3824c1ab64993268cd9165f29c362), decreasing the depht of a layer makes the blocks disappear.
Below depth 10, it's only visible at 2 for some reason.

![depth brokey](https://github.com/user-attachments/assets/61562235-37c8-4717-8cd1-7c93c0c5c609)

**Comment by jacob-grahn** [comment]
I thought just the middle layer from the pr2 import wasn't working, this makes the issue a lot clearer. Should be fixed with the latest commit

**Comment by ctrlraul** [comment]
Looks good now, gg.
