### ISSUE TITLE
gas blocks inactive on depth 16

### ISSUE THREAD

**Issue by jc66266** [jacob-grahn/platform-racing-4#7]
lightbreaking blocks, detectors, and nets don't have any function on depth 16

**Comment by GambitAnimating** [comment]
I believe the issue is because of set_depth function, it sets depth * 2 as well as depth * 2 + 1. 32 possible layers, so when the depth is 16, the gas layers or the layers that are depth * 2 + 1 is set to 33 which isnt allowed.

**Comment by jacob-grahn** [comment]
Sounds like the logic should be `solid_layer = (depth-1) * 2` and `gas_layer = ((depth-1) * 2) + 1`

**Comment by jacob-grahn** [comment]
Should be fixed now, reopen if not!
